name: Run Tests and Deploy Allure Report

on:
  push:
    branches:
      - main 

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Pyrhon 3.09.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
      - name: Set Up Allure
        run: |
          wget -O allure-2.22.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.0/allure-commandline-2.22.0.tgz
          tar -xzf allure-2.22.0.tgz
          sudo mv allure-2.22.0 /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        env:
          ALLURE_RESULTS_DIR: ./allure-results
        run: |
          pytest -v --alluredir=allure-results

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
